### ISSUE TITLE
Fix our spreadsheet mess

### ISSUE THREAD

**Issue by gschare** [cu-mkp/fieldnotes#6]
In our previous attempts at reorganizing the field notes we had several active spreadsheets that were not version controlled and this became very confusing.
This time we have a new plan:
- Generate a new spreadsheet documenting missing URLs. Version control this file and use only this one.
- Create a method for updating the file without overwriting old corrections.
- Go through old spreadsheets documenting missing URLs and corrections and transfer the corrections to the new spreadsheet.

**Comment by njr2128** [comment]
Report from Greg after he fixed the spreadsheet mess:

>Here is the spreadsheet detailing which pages in the field notes wiki appear to be missing (i.e. broken links).
https://github.com/cu-mkp/fieldnotes/blob/main/missing.csv
The information here are the filenames of the page where the missing file was linked, and the name of the missing file itself.
Note that these file names are also the URLs, so you should be able to copy-paste them with the prefix "http://fieldnotes.makingandknowing.org/mainSpace/" and it will work.

> If you manage to locate any of these missing files, you can add the name of the missing file as it appears here and the corrected name to the corrections spreadsheet:
https://github.com/cu-mkp/fieldnotes/blob/main/corrections.csv

> The "missing.csv" spreadsheet is automatically generated, so any edits on it will be overwritten.
The "corrections.csv" spreadsheet is created manually, but it is very important that you edit it as a CSV and remain conscious of special unicode characters. To this end, it is probably best if you simply copy-paste the HTML-quoted URL or unquoted filename into the spreadsheet rather than typing it out manually, because sometimes seemingly-innocuous spaces are not as they appear...

> Once the missing files have been accounted for to our satisfaction or simply ignored, I can get started on moving the files into their new directory structure.

**Comment by gschare** [comment]
I looked through the various spreadsheets leftover from my previous work on this project, diffing them and inspecting GitHub history to find out which were most updated. Eventually this allowed me to prune down to just a few spreadsheets ("missing.csv", "corrections.csv", and "mapping.csv"), as are described above in [Naomi's comment](https://github.com/cu-mkp/fieldnotes/issues/6#issuecomment-848188384).
